# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

@pytest.fixture
def driver():
    driver = webdriver.Firefox()
    driver.maximize_window()
    driver.implicitly_wait(5)
    yield driver
    driver.quit()

def test_lab5(driver):
    base_url = "https://tutorialsninja.com/demo/"
    wait = WebDriverWait(driver, 10)


    # Test data
    first_name_33 = "A" * 33
    last_name_33 = "B" * 33
    valid_first_name = "Arimardan"
    valid_last_name = "Singh"
    email = f"test{int(time.time())}@mail.com"
    telephone = "9876543210"
    password = "Test@123"

    driver.get(base_url)
    assert "Your Store" in driver.title
    driver.find_element(By.LINK_TEXT, "My Account").click()
    driver.find_element(By.LINK_TEXT, "Register").click()

    heading = wait.until(
        EC.visibility_of_element_located((By.XPATH, "//div[@id='content']//h1"))
    ).text
    assert heading == "Register Account"


    # Test Privacy Policy warning
    driver.find_element(By.XPATH, "//input[@value='Continue']").click()
    warning = wait.until(
        EC.visibility_of_element_located((By.CSS_SELECTOR, ".alert-danger"))
    ).text
    assert "Privacy Policy" in warning


    # Fill form with too-long names to trigger validation
    driver.find_element(By.ID, "input-firstname").send_keys(first_name_33)
    driver.find_element(By.ID, "input-lastname").send_keys(last_name_33)
    driver.find_element(By.ID, "input-email").send_keys(email)
    driver.find_element(By.ID, "input-telephone").send_keys(telephone)
    driver.find_element(By.ID, "input-password").send_keys(password)
    driver.find_element(By.ID, "input-confirm").send_keys(password)
    driver.find_element(By.NAME, "agree").click()

    driver.find_element(By.XPATH, "//input[@value='Continue']").click()

    # Check validation errors
    fname_error = driver.find_element(By.XPATH, "//input[@id='input-firstname']/following-sibling::div").text
    lname_error = driver.find_element(By.XPATH, "//input[@id='input-lastname']/following-sibling::div").text
    assert "between 1 and 32 characters" in fname_error
    assert "between 1 and 32 characters" in lname_error


    # Fill valid data and register
    driver.find_element(By.ID, "input-firstname").clear()
    driver.find_element(By.ID, "input-firstname").send_keys(valid_first_name)

    driver.find_element(By.ID, "input-lastname").clear()
    driver.find_element(By.ID, "input-lastname").send_keys(valid_last_name)

    driver.find_element(By.XPATH, "//input[@value='Continue']").click()

    # Verify account creation
    success_text = wait.until(
        EC.visibility_of_element_located((By.XPATH, "//div[@id='content']//h1"))
    ).text
    assert success_text == "Your Account Has Been Created!"

    # Continue to account page
    driver.find_element(By.LINK_TEXT, "Continue").click()

    # Optional: navigate to Order History
    driver.find_element(By.LINK_TEXT, "My Account").click()
    driver.find_element(By.LINK_TEXT, "Order History").click()

    order_heading = wait.until(
        EC.visibility_of_element_located((By.XPATH, "//div[@id='content']//h1"))
    ).text
    assert order_heading == "Order History"
