# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

def test_lab2():
    driver = webdriver.Chrome()
    driver.maximize_window()

    # Open OpenCart demo
    driver.get("https://demo.opencartmart.com/ordercoupon/")
    time.sleep(2)

    # Click on "Laptops & Notebooks"
    driver.find_element(By.LINK_TEXT, "Laptops & Notebooks").click()
    time.sleep(1)

    # Click on "Windows (0)"
    driver.find_element(By.LINK_TEXT, "Windows (0)").click()
    time.sleep(1)

    driver.quit()
