# Generated by Selenium IDE
import time
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select, WebDriverWait


@pytest.fixture
def driver():
    driver = webdriver.Firefox()
    driver.maximize_window()
    yield driver
    driver.quit()


def test_lab4(driver):

    driver.get("https://demo.opencart.com/")

    # Wait for Cloudflare to finish
    WebDriverWait(driver, 20).until(
        lambda d: d.title != "Just a moment..."
    )

    # Verify title
    assert "Your Store" in driver.title

    # Click Desktops
    driver.find_element(By.LINK_TEXT, "Desktops").click()
    time.sleep(2)

    # Click Mac (1)
    driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    time.sleep(2)

    # Verify Mac heading
    assert driver.find_element(By.TAG_NAME, "h2").text == "Mac"

    # Sort By Name (A - Z)
    Select(driver.find_element(By.ID, "input-sort")) \
        .select_by_visible_text("Name (A - Z)")
    time.sleep(2)

    # Add to Cart
    driver.find_element(
        By.CSS_SELECTOR, ".button-group > button:first-child"
    ).click()
    time.sleep(2)

    # Search Mobile
    search = driver.find_element(By.NAME, "search")
    search.clear()
    search.send_keys("Mobile")
    driver.find_element(By.CSS_SELECTOR, "#search button").click()
    time.sleep(2)

    # Search Monitors with description
    search = driver.find_element(By.ID, "input-search")
    search.clear()
    search.send_keys("Monitors")
    driver.find_element(By.NAME, "description").click()
    driver.find_element(By.ID, "button-search").click()
    time.sleep(2)
