# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBrowsernavigationtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_browsernavigationtest(self):
    self.driver.get("https://tutorialsninja.com/demo/")
    self.driver.set_window_size(1062, 809)
    self.vars["homeTitle"] = self.driver.title
    print(str(self.vars["homeTitle"]))
    self.driver.find_element(By.CSS_SELECTOR, ".list-inline .dropdown-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    time.sleep(1)
    self.vars["loginTitle"] = self.driver.title
    print(str(self.vars["loginTitle"]))
    self.driver.get("https://tutorialsninja.com/demo//")
    self.vars["backTitle"] = self.driver.title
    print(str(self.vars["backTitle"]))
    self.driver.get("https://tutorialsninja.com/demo/   /index.php?route=account/login")
    self.vars["forwardTitle"] = self.driver.title
    print(str(self.vars["forwardTitle"]))
    self.driver.get("https://tutorialsninja.com/demo//index.php?route=account/login")
    self.vars["refreshTitle"] = self.driver.title
    print(str(self.vars["refreshTitle"]))
    self.driver.close()
  
