# Generated by Selenium IDE
import time
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select

def test_lab3():
    # Setup WebDriver
    driver = webdriver.Chrome()
    driver.maximize_window()

    # Open OpenCart demo
    driver.get("https://demo.opencartmart.com/ordercoupon/")
    time.sleep(2)

    # Click on "Desktops"
    driver.find_element(By.LINK_TEXT, "Desktops").click()
    time.sleep(1)

    # Click on "Mac (1)"
    driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    time.sleep(1)

    # Open sort dropdown
    sort_dropdown = driver.find_element(By.ID, "input-sort")
    sort_dropdown.click()
    time.sleep(1)

    # Select "Name (A - Z)"
    select = Select(sort_dropdown)
    select.select_by_visible_text("Name (A - Z)")
    time.sleep(2)

    # Close browser
    driver.quit()
